[package]
name = "diffpatch"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
walkdir = "2.5"
diffy = "0.4"
nu-ansi-term = "0.50"

[patch.crates-io]
diffy = { path = "/home/jakob/dev/rust/contrib/diffy" }